# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# Minecraft
minecraft_version=26.2
minecraft_dependency=>=26.2 <26.3
minecraft_suffix=mc26.2
java_target=25
java_dependency=>=25

# Fabric
fabric_loader_version=0.19.3
fabric_loader_dependency=>=0.18.0
fabric_api_version=0.153.0+26.2
fabric_api_dependency=*

# Mixin
mixin_minimum_version=0.8
mixin_package=mixin
mixin_compatibility_level=JAVA_17

# Mod properties
mod_name=SuperMartijn642's Config Library
mod_description=Config Lib makes dealing with config files just a bit easier.
mod_id=supermartijn642configlib
mod_version=1.1.8
mod_license=All rights reserved
mod_page=https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib
mod_sources=https://github.com/SuperMartijn642/SuperMartijn642sConfigLib
mod_issues=https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/issues
mod_package=com.supermartijn642.configlib
mod_main_class=ConfigLib
mod_client_class=ConfigLibClient
maven_group=com.supermartijn642

# Publishing
publishing_release_type=stable
publishing_game_versions=26.2
curseforge_project_id=438332
curseforge_required_dependency_ids=fabric-api
curseforge_optional_dependency_ids=
modrinth_project_id=LN9BxssP
modrinth_required_dependency_ids=fabric-api
modrinth_optional_dependency_ids=
